default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: yodit
  password: 123456

development:
  <<: *default
  database: budget_app_development


test:
  <<: *default
  database: budget_app_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
